# Generated by Django 4.2.11 on 2024-03-14 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200, unique=True)),
                ('prior_reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post_reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reading_difference', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
